name = "CTOptimization"
uuid = "22f08de8-270f-4470-8fba-397dbc90d8e0"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.1.6"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CTBase = "0.5"
LinearAlgebra = "1.8"
Printf = "1.8"
julia = "1.8"
